[build]
command = 'npm run build'
publish = 'build'

# setting env `AWS_LAMBDA_JS_RUNTIME=nodejs14.x` here doesn't work, see:
# https://github.com/sveltejs/kit/issues/2687#issuecomment-951257050
# https://answers.netlify.com/t/aws-lambda-js-runtime-nodejs14-x/32161/2

# workaround: https://github.com/sveltejs/kit/issues/2687#issuecomment-951188975
[functions]
node_bundler = 'esbuild'
